Category ItemList site styling 80%
TheAyes/Food-Buddy pull request #32
Opened 2023-06-28 12:11 UTC by vanessa-truong

2023-06-28 12:30 UTC, TheAyes requested changes

2023-06-28 12:30 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +		padding: 7px 0 0 7px;
Padding oben und links? die Reihenfolge ist: Oben, Rechts, Unten, Links

2023-06-28 12:30 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +	}
Bereits global spezifiziert, also überflüssig.

2023-06-28 12:30 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +		height: 13vh;
Irgendwie ein bisschen seltsam, dass mit `vw`/`vh` zu machen. meistens lässt man die height absolut unangefasst und regelt dann nur die width. Das erfordert aber, dass der Eltern-Container die gewünschte breite hat.
```suggestion
	.itemImages {
		max-width: 100%;
```

2023-06-28 12:30 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +		margin-left: 15vw;
margin bitte nicht relativ angeben. 
```suggestion
       padding: 2rem 0;
		margin-left: 50px;
```

2023-06-28 12:30 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +	}, [jsonData]);
Wird dann später durch die mongo id ersetzt

2023-06-28 12:30 UTC, TheAyes commented on client/src/pages/ItemList/ItemList.module.scss
> +	grid-template-rows: 5vh, 5vh, 5vh;
Warum so? :o 
```suggestion
	grid-template-rows: 5vh;
```

2023-06-28 12:30 UTC, TheAyes commented on client/src/pages/ItemList/ItemList.module.scss
> +	grid-template-columns: repeat(3, 1fr);
Kann man ein wenig responsiver machen mit grid-auto-columns
```suggestion
	grid-auto-columns: minmax(50px, 150px); // Passe die minimum bzw maximum Werte an so wie du es brauchst
```

2023-06-28 12:30 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +	console.log(products);
Nicht vergesen das zu entfernen. Nur für die Entwicklung wichtig, in der Produktion wollen wir das nicht haben.
```suggestion
```

2023-06-28 12:37 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +		height: 13vh;
```suggestion
	.itemImages {
	        aspect-ratio: 1/1;
		width: 5rem;
		height: auto;
```

2023-06-28 12:45 UTC, vanessa-truong commented on client/src/components/ProductItems/ProductItems.module.scss
> +		height: 13vh;
habe noch ne height: 10rem vergeben, sonst sind die bilder unterschiedlich hoch. so passts aber

2023-06-28 12:45 UTC, vanessa-truong commented on client/src/components/ProductItems/ProductItems.module.scss
> +	}
habs gelöscht

2023-06-28 12:46 UTC, vanessa-truong commented on client/src/components/ProductItems/ProductItems.module.scss
> +		padding: 7px 0 0 7px;
padding: 7px gemacht

2023-06-28 12:50 UTC, vanessa-truong commented on client/src/pages/ItemList/ItemList.module.scss
> +	grid-template-rows: 5vh, 5vh, 5vh;
Bitte lassen, hat sich mies verschoben bei nur 1 mal 5vh, i dont know why

2023-06-30 07:56 UTC, TheAyes requested changes

2023-06-30 07:56 UTC, TheAyes commented on client/src/components/ProductItems/ProductItems.module.scss
> +		margin-right: 2%;
Paddings, margins und höhen wenns geht nicht in sondern rem oder px.
Grund ist, dass Prozente hier total unvorhersehbar sind und nur chaos stiften.

2023-06-30 07:56 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +	}, [jsonData]);
Mittlerweile kannst du die Daten ja aus der Datenbank holen. Am einfachsten machst du das dann mit Axios :o

2023-06-30 07:56 UTC, TheAyes commented on client/src/pages/ItemList/item-list.jsx
> +						key={product.id}
das wäre dann
```suggestion
						key={product._id}
```

2023-07-03 07:53 UTC, merged