goBack Button Styling
TheAyes/Food-Buddy pull request #36
Opened 2023-06-29 08:37 UTC by supermazlum

styling noch nicht vollständig (farbe und größe). wird noch nach absprache mit team angepasst.

2023-06-30 08:15 UTC, TheAyes requested changes

2023-06-30 08:15 UTC, TheAyes commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +// };
Sehr viel Kommentar

2023-06-30 08:15 UTC, TheAyes commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +    )
```suggestion
    return <button className={styles.addCartButton} onClick={addToCart}>Add to Cart</button>
```

2023-06-30 08:15 UTC, TheAyes commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +// }
Seeeeehr viel Kommentar

2023-06-30 08:15 UTC, TheAyes commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +        font-weight: 400;
Soll nur beim hovern dick werden?
So oder so, eher ne Variable nutzen.
```suggestion
        font-weight: $fw-regular;
```

2023-06-30 08:25 UTC, supermazlum commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +// };
done!

2023-06-30 08:27 UTC, supermazlum commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +    )
habs so gelassen

2023-06-30 08:28 UTC, supermazlum commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +// }
done!

2023-06-30 08:30 UTC, supermazlum commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +        font-weight: 400;
done!

2023-07-03 07:37 UTC, TheAyes submitted a review, later dismissed

2023-07-03 07:54 UTC, TheAyes submitted a review, later dismissed

2023-07-03 07:55 UTC, TheAyes approved these changes

2023-07-03 07:56 UTC, merged