like button angelegt, funktionslogik fehlt noch, um es bei klick der …
TheAyes/Food-Buddy pull request #38
Opened 2023-06-29 11:11 UTC by supermazlum

…wishlist hinzuzufügen

2023-06-30 13:26 UTC, TheAyes requested changes

2023-06-30 13:26 UTC, TheAyes commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +// };
Zu viel Kommentar

2023-06-30 13:26 UTC, TheAyes commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +        font-weight: 400;
Font weight auf Hover? Und dann noch ohne variable? :)
```suggestion
        font-weight: $fw-regular;
```

2023-06-30 13:26 UTC, TheAyes commented on client/src/variable.scss
> +$fw-bold: 700;
Hier müsstest du noch die `$fw-light`hinzufügen.
Und Medium und regular sind vertauscht:
```suggestion
// Variablen für Font-Weights
$fw-light: 300;
$fw-regular: 400;
$fw-medium: 500;
$fw-bold: 700;
```

2023-07-01 13:11 UTC, supermazlum commented on client/src/components/AddToCartComponent/AddToCartComponent.jsx
> +// };
done!

2023-07-01 13:12 UTC, supermazlum commented on client/src/components/GoBackButton/GoBackButton.module.scss
> +        font-weight: 400;
done!

2023-07-01 13:13 UTC, supermazlum commented on client/src/variable.scss
> +$fw-bold: 700;
done! das mit regular und medium checke ich nicht, dritte mal schon korrigiert. der kleine möchte doch groß bleiben wahrscheinlich. ist erledigt ;) ...hoffentlich diesmal

2023-07-03 07:58 UTC, closed without merging