16 detailseite produkt
TheAyes/Food-Buddy pull request #46
Opened 2023-07-03 13:19 UTC by supermazlum

2023-07-03 16:06 UTC, TheAyes requested changes

2023-07-03 16:06 UTC, TheAyes commented on client/src/app.jsx
> +			<CartPage />
Nich machen diese
```suggestion
			<CartPage />
```
```suggestion
```

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/CartItem/CartItem.jsx
> +					<h3 className={styles.reviewIndicator}>({numOfRatings})</h3>
Sollte eher ein `<p>` sein denke ich

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/CartItem/CartItem.jsx
> +					<h2 className={styles.priceIndicator}>{price}</h2>
Auch eher ein `<p>`

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/GoBackButton/GoBackButton.module.scss
>      height: 4vh;
Das kann ich für dich machen :D
```suggestion
// ACHTUNG: da es jetzt ein Button ist, müssen Background und border auf 'none' gesetzt werden. Beim styling bitte erneut anpassen"

.goBackButton {
    width: 2.5vw;
    height: 4vh;
    
    background: none;
    border: none;
```

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/LikeButton/LikeButton.jsx
> +// Import Images
denke nicht, dass ein Kommentar hier nötig ist? :o
```suggestion
```

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/WishItem/WishItem.jsx
> +// Import Images
```suggestion
import { LikeButton } from '../LikeButton/LikeButton';
```

2023-07-03 16:06 UTC, TheAyes commented on client/src/components/WishItem/WishItem.jsx
> +					<h3 className={styles.reviewIndicator}>({numOfRatings})</h3>
sind auch eher `<p>`

2023-07-03 16:06 UTC, TheAyes commented on client/src/pages/MyCartPage/cart-page.jsx
> +					<h4>Warenkorb</h4>
du magst `<h>` oder?

2023-07-04 13:19 UTC, supermazlum commented on client/src/components/CartItem/CartItem.jsx
> +					<h3 className={styles.reviewIndicator}>({numOfRatings})</h3>
done!

2023-07-04 13:20 UTC, supermazlum commented on client/src/components/CartItem/CartItem.jsx
> +					<h2 className={styles.priceIndicator}>{price}</h2>
done!

2023-07-04 13:20 UTC, supermazlum commented on client/src/components/GoBackButton/GoBackButton.module.scss
>      height: 4vh;
komplett neu gestylt inzwischen!

2023-07-04 13:22 UTC, supermazlum commented on client/src/components/LikeButton/LikeButton.jsx
> +// Import Images
ich mag das so

2023-07-04 13:25 UTC, supermazlum commented on client/src/components/WishItem/WishItem.jsx
> +// Import Images
ist wech!

2023-07-04 13:27 UTC, supermazlum commented on client/src/components/WishItem/WishItem.jsx
> +					<h3 className={styles.reviewIndicator}>({numOfRatings})</h3>
done!

2023-07-04 13:27 UTC, supermazlum commented on client/src/pages/MyCartPage/cart-page.jsx
> +					<h4>Warenkorb</h4>
es ist eher so, das <h>'s mich mögen. ich kann da gar nix für

2023-07-07 12:02 UTC, merged